// Problem 2
// =========
// 
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
//                   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.

function run() {
    var sum = 0, x = 1, y = 2;
    while (x <= 4000000) {
        if (x % 2 == 0) {
            sum += x;
        }
        var z = x + y;
        x = y;
        y = z;
    }
    return sum;
}

// TODO: return your answer for this prompt.
return run();