// Problem 45
// ==========
// 
// Triangle, pentagonal, and hexagonal numbers are generated by the following
// formulae:
// 
// Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
// Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
// Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...
// 
// It can be verified that T[285] = P[165] = H[143] = 40755.
// 
// Find the next triangle number that is also pentagonal and hexagonal.
var bigInt = require("big-integer");

const isPentagonal = (n) => ((Math.sqrt(24 * n + 1) + 1) / 6) % 1 === 0;

const isHexagonal = (n) => ((Math.sqrt((8 * n) + 1) + 1) / 4) % 1 === 0;

// Starting from just beyond the known triangle 'n' ...
for (var i = 286;; i++) {
    var T = new bigInt(i + 1).multiply(i).divide(2).toJSNumber();
    if (isPentagonal(T) && isHexagonal(T)) {
        return T;
    }
}