// Problem 2
// =========
// 
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 
//                   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// Find the sum of all the even-valued terms in the sequence which do not
// exceed four million.
// Answer: 4613732

function run(threshold) {
    var sum = 0, x = 0, y = 1;
    while (x <= threshold) {
        if (x % 2 == 0) {
            sum += x;
        }
        [x, y] = [x + y, x];
    }
    return sum;
}

// TODO: return your answer for this prompt.
var result = run(4000000);